-- ==============================================================================
-- RESTORE CANONICAL MASTER DATA & OPERATIONAL INSTRUCTIONS (68 FUNDS)
-- ==============================================================================
-- Run this script in the Supabase SQL Editor to immediately restore all 68 funds,
-- their correct settlement rules (T0 vs T1), schedules, and Arabic operational instructions.
-- This script preserves any existing NAV prices (> 0) and user IDs.
-- ==============================================================================

BEGIN;

-- 1. UPDATE / RESTORE REFERENCE DATA (68 CANONICAL FUNDS)
INSERT INTO public.reference_data (symbol_code, symbol_name, actual_symbol, email_contact, nav_unit_price, fund_type, status) VALUES
('1001', 'AZ - IDKHAR', 'ADKHAR-AZ', 'ادخار /  AZFI', 0, 'T0', 'ACTIVE'),
('100-100', 'Beltone EGX100 Fund', 'Tharawat - 100/100', 'Beltone EGX100 - Tharawat 100/100', 0, 'T1', 'ACTIVE'),
('1004', 'Ataa Charity Fund', 'ATAA', 'Ataa Fund', 0, 'T0', 'ACTIVE'),
('1005', 'Al-Siola Fund-NI Capital', 'NICapital', 'SIULA fund - NI MM FUND', 0, 'T0', 'ACTIVE'),
('1006', 'Aafaq Investment Fund', 'AFAC', 'Afaaq Fund', 0, 'T1', 'ACTIVE'),
('1010', 'AZ - FORAS', 'Azimut Stocks', 'Azimut Equity Opportunity Fund', 0, 'T1', 'ACTIVE'),
('1011', 'Wethaq Investment', 'IEIG', 'Wethaq M.M', 0, 'T0', 'ACTIVE'),
('1012', 'AZ - Estehkak T27 USD', 'STRC', 'Azimut Target Maturity - USD', 0, 'T0', 'CLOSED'),
('1014', 'Misr Tkaful Money Market', 'Misr Takaful', 'Misr Takaful Fund', 0, 'T0', 'ACTIVE'),
('1015', 'CIAM Misr Equity', 'EQTY-', 'Misr Equity - CIAM Fund', 0, 'T1', 'ACTIVE'),
('1016', 'Cash Mubasher Fund', 'CashMubasher', 'Cash Mubasher Fund Price', 0, 'T0', 'ACTIVE'),
('1017', 'Istsmar w Aman', 'Estesmar-Aman', 'Misr Insurance  (Istithmar & Aman)', 0, 'T1', 'ACTIVE'),
('1018', 'HORUS - AFIM', 'Horus', 'Horas MM', 0, 'T0', 'ACTIVE'),
('1020', 'Misr Al Mostakbal', 'MOSTAKBAL', 'MOSTAKBAL FUND', 0, 'T1', 'ACTIVE'),
('1021', 'CIAM - Misr Al Youmy', 'Misr Al-Youm', 'Misr Al-Youm', 0, 'T0', 'ACTIVE'),
('AHLAC', 'Tamayoz - AFIM', 'AHLAC', 'Tamyouz MMF', 0, 'T0', 'ACTIVE'),
('Al Hayah', 'NBK Al-Hayah', 'AlHayah', 'AlHayah - Hayat', 0, 'T1', 'ACTIVE'),
('Almezan', 'NBK Al-Mizan', 'Almezan', 'Al Mizan', 0, 'T1', 'ACTIVE'),
('ARUP', 'Arope Money Market', 'AROPE', 'AROPE Insurance Misr Fund', 0, 'T0', 'CLOSED'),
('Belton USD', 'Beltone Fixed Income USD', 'Belton USD', 'BAM FI USD', 0, 'T1', 'ACTIVE'),
('B-Secure', 'Beltone Fixed Income EGP', 'B-Secure', 'B-Secure', 0, 'T0', 'ACTIVE'),
('CI MANAGEMENT', 'CI-ctor Consuming', 'CI MANAGEMENT', 'CIAM Sectors Prices - CI MANAGEMENT', 0, 'T1', 'ACTIVE'),
('CIAM Building', 'CI-ctor Building', 'CIAM Building', 'CIAM Sectors Prices - CIAM Building', 0, 'T1', 'ACTIVE'),
('CIAM Digital Pay', 'CI-ctor Digital Pay', 'CIAM Digital Pay', 'CIAM Sectors Prices - CIAM Digital Pay', 0, 'T1', 'ACTIVE'),
('CIAM Exporting', 'CI-ctor Exporting', 'CIAM Exporting', 'CIAM Sectors Prices - CIAM Exporting', 0, 'T1', 'ACTIVE'),
('CIAM Technology', 'CI-ctor Technology', 'CIAM Technology', 'CIAM Sectors Prices - CIAM Technology', 0, 'T1', 'ACTIVE'),
('Consumer', 'Beltone Consumer Fund', 'Tharawat - Consumer', 'Beltone Sectors Price / Tharawat – Consumer', 0, 'T1', 'ACTIVE'),
('Dahab', 'Dahab - AFIM', 'DAHAB', 'Dahab AL-Ahly', 0, 'T1', 'ACTIVE'),
('Delta Insurance Fund', 'Delta Life Assurance', 'DLTAF', 'Delta life assurance MM', 0, 'T0', 'ACTIVE'),
('EGYMUBMCA', 'EGYMUBMCA', 'EGYMUBMCA', 'Cash Mubasher Fund Price', 0, 'T0', 'ACTIVE'),
('FANAR', 'El Fanar Cash Fund', 'FANAR', 'Fanar fund', 0, 'T0', 'ACTIVE'),
('Financial', 'Beltone Financial Fund', 'Tharawat - Financial', 'Beltone Sectors Price / Tharawat – Financial', 0, 'T1', 'ACTIVE'),
('GIG FUND', 'GIG Money Market', 'GIG FUND', 'GIG MM', 0, 'T0', 'ACTIVE'),
('GOLD AZ', 'AZ - Gold', 'Gold AZ', 'AZ-GOLD', 0, 'T1', 'ACTIVE'),
('GOSOR', 'Gosour Equity  Cumulativ', 'GOSOR', 'Josour Fund', 0, 'T1', 'ACTIVE'),
('Industrial', 'Beltone Industrial Fund', 'Tharawat - industrial', 'Beltone Sectors Price / Tharawat – industrial', 0, 'T1', 'ACTIVE'),
('Ishraq', 'NBK Money Market', 'Ishraq', 'ISHRAQ', 0, 'T0', 'ACTIVE'),
('ISKAN', 'Iskan - Kol Youm', 'ISKAN FUND', 'ISKAN MM', 0, 'T1', 'ACTIVE'),
('Kenz - foras', 'Kenz Foras AAIH', 'KENZFORAS', 'Kenz 1st - Foras - KENZFORAS', 0, 'T1', 'ACTIVE'),
('kenzshariaa', 'Kenz Shariah', 'KENZSHARIAA', 'Kenz-Shareiaa - KENZSHARIAA', 0, 'T1', 'ACTIVE'),
('Maksab OZ', 'Maksab OZ USD', 'Maksab OZ', 'Maksab-OZ USD', 0, 'T1', 'ACTIVE'),
('Momentum', 'Cairo Capital Cumulative', 'Momentum', 'Cairo Capital cumulative fund- Momentum', 0, 'T1', 'ACTIVE'),
('Mubasher Equity Fund', 'Mubasher Equity Fund', 'Mubasher Equity', 'Mubasher Equity Fund Price', 0, 'T1', 'ACTIVE'),
('Mubasher Gold', 'Dahab Mubasher', 'Mubasher Gold', 'Dahab Mubasher - Mubasher Gold', 0, 'T1', 'ACTIVE'),
('NAMAA Invest', 'NBK Namaa', 'NAMAA', 'NAMAA', 0, 'T1', 'ACTIVE'),
('ODIN IV', 'Odin Money Market', 'ODIN IV', 'ODIN MMF', 0, 'T0', 'ACTIVE'),
('Real-Estate', 'Beltone Real Estate Fund', 'Tharawat - Real estate', 'Beltone Sectors Price / Tharawat – Real estate', 0, 'T1', 'ACTIVE'),
('Sabayek', 'Sabayek - Belton', 'Sabayek', 'Sabayek', 0, 'T1', 'ACTIVE'),
('Sarwaty Fund', 'Sarwaty Fund', 'Sarwaty Fund', 'Sarwaty Fund', 0, 'T0', 'CLOSED'),
('Shariah Compliant Fund', 'CIAM -  Shariah Equity', 'Shariah Compliant Fund', 'Misr Shariaa Equity Price', 0, 'T1', 'ACTIVE'),
('Stream Fund', 'Cairo Capital Fixed Inc', 'Stream', 'Cairo Capital Fixed income – Stream Fund', 0, 'T1', 'ACTIVE'),
('Target First', 'Target Fixed Income Fund', 'Target First', 'Target MM  -Target First', 0, 'T0', 'ACTIVE'),
('TREND', 'Odin Equity Fund', 'TREND', 'Trend Fund', 0, 'T1', 'ACTIVE'),
('Wafra', 'Beltone EGX33 Shariah', 'Tharawat - Wafra', 'Beltone EGX33 - Tharawat Wafra', 0, 'T1', 'ACTIVE'),
('WELADNA', 'Weladna Charity fund', 'WELADNA', 'Weladna', 0, 'T0', 'ACTIVE'),
('Zaldi Star', 'Zaldi Money Market', 'Zaldi Star', 'Zaldi Star MMF', 0, 'T0', 'ACTIVE'),
('Zaldi El Masry', 'Zaldi El Masry Fund', 'ZALDI-MSRY', 'Zaldi El Masry Fund PRICE', 0, 'T1', 'ACTIVE'),
('CI 20HD 7', 'CI 20HD 7', 'CI 20HD 7', 'CIAM Sectors Prices - CIAM 7 Issue - 20HD', 0, 'T1', 'ACTIVE'),
('CI SEC 8', 'CI SEC 8', 'CI Sec 8', 'CIAM Sectors Prices - CIAM 8 Issue - IPO', 0, 'T1', 'ACTIVE'),
('CI THEQUANT 6', 'CI THEQUANT 6', 'CI TheQuant 6', 'CIAM Sectors Prices - CIAM 6 Issue - The Quant', 0, 'T1', 'ACTIVE'),
('Mubasher USD', 'Dollar Mubasher FI Fund', 'Dollar Mubasher', 'Dollar Mubasher Investment Fund Price', 0, 'T0', 'ACTIVE'),
('AlShakmagya', 'Bokra Gold', 'AlShakmagya', 'Bokra Gold fund (Shakmajiya)', 0, 'T1', 'ACTIVE'),
('Mubasher Fadda', 'Mubasher Silver Fund', 'Fadda Mubasher', 'Mubsher Silver price', 0, 'T1', 'ACTIVE'),
('Bareeq', 'Bareeq fund', 'Bareeq', 'Bariq fund price', 0, 'T1', 'ACTIVE'),
('PFI Cashi', 'PFI Cashi fund', 'PFI Cashi', 'PFI Cashi', 0, 'T0', 'ACTIVE'),
('Kenz EGX70', 'Kenz EGX70', 'Kenz EGX70', 'Kenz EGX70', 0, 'T1', 'ACTIVE'),
('Kenz EGX 35 LV', 'Kenz EGX 35 LV', 'Kenz EGX 35 LV', 'Kenz EGX 35 LV', 0, 'T1', 'ACTIVE'),
('Granite fund', 'Granite fund', 'Granite fund', 'Granite fund price', 0, 'T0', 'ACTIVE')
ON CONFLICT (symbol_code) DO UPDATE SET
    symbol_name = EXCLUDED.symbol_name,
    actual_symbol = EXCLUDED.actual_symbol,
    fund_type = EXCLUDED.fund_type,
    email_contact = EXCLUDED.email_contact,
    status = EXCLUDED.status,
    nav_unit_price = CASE 
        WHEN reference_data.nav_unit_price > 0 THEN reference_data.nav_unit_price 
        ELSE EXCLUDED.nav_unit_price 
    END;

-- 2. RE-INITIALIZE / RESTORE FUND SCHEDULES (EXACT ARABIC OPERATIONAL RULES)
DELETE FROM public.fund_schedules;

INSERT INTO public.fund_schedules (fund_code, fund_type, frequency, buy_days, sell_days, notice_lead_day, notice_cutoff_time, raw_instruction, status) VALUES
('1001', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+0', 'ACTIVE'),
('100-100', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('1004', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'خيري', 'ACTIVE'),
('1005', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+0', 'ACTIVE'),
('1006', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('1010', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('1011', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('1012', 'T0', 'CLOSED', '[]'::jsonb, '[]'::jsonb, 'NONE', '12:00', 'closed', 'CLOSED'),
('1014', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('1015', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('1016', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+0', 'ACTIVE'),
('1017', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('1018', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('1020', 'T1', 'WEEKLY', '["SUN"]'::jsonb, '["SUN"]'::jsonb, 'THURSDAY', '14:00', 'اسبوعي بيتم ارسال اخطار الخميس وبيتم التنفيذ الاحد', 'ACTIVE'),
('1021', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('AHLAC', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('Al Hayah', 'T1', 'WEEKLY', '["SUN"]'::jsonb, '["SUN"]'::jsonb, 'THURSDAY', '14:00', 'اسبوعي بيتم ارسال اخطار الخميس وبيتم التنفيذ الاحد', 'ACTIVE'),
('Almezan', 'T1', 'WEEKLY', '["SUN"]'::jsonb, '["SUN"]'::jsonb, 'THURSDAY', '14:00', 'اسبوعي بيتم ارسال اخطار الخميس وبيتم التنفيذ الاحد', 'ACTIVE'),
('ARUP', 'T0', 'CLOSED', '[]'::jsonb, '[]'::jsonb, 'NONE', '12:00', 'closed', 'CLOSED'),
('Belton USD', 'T1', 'BIWEEKLY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["2ND_MON","4TH_MON"]'::jsonb, 'NONE', '12:00', 'شراء T+1&البيع يوم الاثنين فى ثاني اسبوع ورابع اسبوع من كل شهر', 'ACTIVE'),
('B-Secure', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+0', 'ACTIVE'),
('CI MANAGEMENT', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('CIAM Building', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('CIAM Digital Pay', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('CIAM Exporting', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('CIAM Technology', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('Consumer', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('Dahab', 'T1', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 'T+1', 'ACTIVE'),
('Delta Insurance Fund', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('EGYMUBMCA', 'T0', 'DAILY', '["SUN","MON","TUE","WED","THU"]'::jsonb, '["SUN","MON","TUE","WED","THU"]'::jsonb, 'NONE', '12:00', 't+0', 'ACTIVE'),
('FANAR', 'El Fanar Cash Fund', 'FANAR', 'Fanar fund', 0, 'T0', 'ACTIVE'),
('Financial', 'Beltone Financial Fund', 'Tharawat - Financial', 'Beltone Sectors Price / Tharawat – Financial', 0, 'T1', 'ACTIVE'),
('GIG FUND', 'GIG Money Market', 'GIG FUND', 'GIG MM', 0, 'T0', 'ACTIVE'),
('GOLD AZ', 'AZ - Gold', 'Gold AZ', 'AZ-GOLD', 0, 'T1', 'ACTIVE'),
('GOSOR', 'Gosour Equity  Cumulativ', 'GOSOR', 'Josour Fund', 0, 'T1', 'ACTIVE'),
('Industrial', 'Beltone Industrial Fund', 'Tharawat - industrial', 'Beltone Sectors Price / Tharawat – industrial', 0, 'T1', 'ACTIVE'),
('Ishraq', 'NBK Money Market', 'Ishraq', 'ISHRAQ', 0, 'T0', 'ACTIVE'),
('ISKAN', 'Iskan - Kol Youm', 'ISKAN FUND', 'ISKAN MM', 0, 'T1', 'ACTIVE'),
('Kenz - foras', 'Kenz Foras AAIH', 'KENZFORAS', 'Kenz 1st - Foras - KENZFORAS', 0, 'T1', 'ACTIVE'),
('kenzshariaa', 'Kenz Shariah', 'KENZSHARIAA', 'Kenz-Shareiaa - KENZSHARIAA', 0, 'T1', 'ACTIVE'),
('Maksab OZ', 'Maksab OZ USD', 'Maksab OZ', 'Maksab-OZ USD', 0, 'T1', 'ACTIVE'),
('Momentum', 'Cairo Capital Cumulative', 'Momentum', 'Cairo Capital cumulative fund- Momentum', 0, 'T1', 'ACTIVE'),
('Mubasher Equity Fund', 'Mubasher Equity Fund', 'Mubasher Equity', 'Mubasher Equity Fund Price', 0, 'T1', 'ACTIVE'),
('Mubasher Gold', 'Dahab Mubasher', 'Mubasher Gold', 'Dahab Mubasher - Mubasher Gold', 0, 'T1', 'ACTIVE'),
('NAMAA Invest', 'NBK Namaa', 'NAMAA', 'NAMAA', 0, 'T1', 'ACTIVE'),
('ODIN IV', 'Odin Money Market', 'ODIN IV', 'ODIN MMF', 0, 'T0', 'ACTIVE'),
('Real-Estate', 'Beltone Real Estate Fund', 'Tharawat - Real estate', 'Beltone Sectors Price / Tharawat – Real estate', 0, 'T1', 'ACTIVE'),
('Sabayek', 'Sabayek - Belton', 'Sabayek', 'Sabayek', 0, 'T1', 'ACTIVE'),
('Sarwaty Fund', 'Sarwaty Fund', 'Sarwaty Fund', 'Sarwaty Fund', 0, 'T0', 'CLOSED'),
('Shariah Compliant Fund', 'CIAM -  Shariah Equity', 'Shariah Compliant Fund', 'Misr Shariaa Equity Price', 0, 'T1', 'ACTIVE'),
('Stream Fund', 'Cairo Capital Fixed Inc', 'Stream', 'Cairo Capital Fixed income – Stream Fund', 0, 'T1', 'ACTIVE'),
('Target First', 'Target Fixed Income Fund', 'Target First', 'Target MM  -Target First', 0, 'T0', 'ACTIVE'),
('TREND', 'Odin Equity Fund', 'TREND', 'Trend Fund', 0, 'T1', 'ACTIVE'),
('Wafra', 'Beltone EGX33 Shariah', 'Tharawat - Wafra', 'Beltone EGX33 - Tharawat Wafra', 0, 'T1', 'ACTIVE'),
('WELADNA', 'Weladna Charity fund', 'WELADNA', 'Weladna', 0, 'T0', 'ACTIVE'),
('Zaldi Star', 'Zaldi Money Market', 'Zaldi Star', 'Zaldi Star MMF', 0, 'T0', 'ACTIVE'),
('Zaldi El Masry', 'Zaldi El Masry Fund', 'ZALDI-MSRY', 'Zaldi El Masry Fund PRICE', 0, 'T1', 'ACTIVE'),
('CI 20HD 7', 'CI 20HD 7', 'CI 20HD 7', 'CIAM Sectors Prices - CIAM 7 Issue - 20HD', 0, 'T1', 'ACTIVE'),
('CI SEC 8', 'CI SEC 8', 'CI Sec 8', 'CIAM Sectors Prices - CIAM 8 Issue - IPO', 0, 'T1', 'ACTIVE'),
('CI THEQUANT 6', 'CI THEQUANT 6', 'CI TheQuant 6', 'CIAM Sectors Prices - CIAM 6 Issue - The Quant', 0, 'T1', 'ACTIVE'),
('Mubasher USD', 'Dollar Mubasher FI Fund', 'Dollar Mubasher', 'Dollar Mubasher Investment Fund Price', 0, 'T0', 'ACTIVE'),
('AlShakmagya', 'Bokra Gold', 'AlShakmagya', 'Bokra Gold fund (Shakmajiya)', 0, 'T1', 'ACTIVE'),
('Mubasher Fadda', 'Mubasher Silver Fund', 'Fadda Mubasher', 'Mubsher Silver price', 0, 'T1', 'ACTIVE'),
('Bareeq', 'Bareeq fund', 'Bareeq', 'Bariq fund price', 0, 'T1', 'ACTIVE'),
('PFI Cashi', 'PFI Cashi fund', 'PFI Cashi', 'PFI Cashi', 0, 'T0', 'ACTIVE'),
('Kenz EGX70', 'Kenz EGX70', 'Kenz EGX70', 'Kenz EGX70', 0, 'T1', 'ACTIVE'),
('Kenz EGX 35 LV', 'Kenz EGX 35 LV', 'Kenz EGX 35 LV', 'Kenz EGX 35 LV', 0, 'T1', 'ACTIVE'),
('Granite fund', 'Granite fund', 'Granite fund', 'Granite fund price', 0, 'T0', 'ACTIVE');

-- 3. AUDIT LOG ENTRY
INSERT INTO public.audit_logs (
    id,
    action,
    entity_name,
    entity_id,
    user_name,
    ip_address,
    new_values,
    created_at
) VALUES (
    uuid_generate_v4(),
    'RESTORE_CANONICAL_MASTER_DATA',
    'REFERENCE_DATA',
    'CANONICAL_FUNDS_RESTORE',
    'System Admin (SQL Script)',
    '127.0.0.1',
    '{"status":"SUCCESS","funds_count":68,"reason":"Restored operational schedules, T0/T1 types, and instructions from canonical master"}'::jsonb,
    TIMEZONE('utc', NOW())
);

COMMIT;
